spring.application.name=Generador

spring.datasource.url=jdbc:postgresql://localhost:5432/generador_reportes
spring.datasource.username=postgres
spring.datasource.password=123456789

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=4231